Changes related to i4Trust
FIWARE/helm-charts pull request #31
Opened 2021-06-09 12:14 UTC by dwendland

Updating charts of API Umbrella, BAE and Keyrock to be compatible with FIWARE Release 8.0 app versions

2021-06-09 13:15 UTC, wistefan requested changes
Please check if the configmaps with tokens or certs should be secrets.

2021-06-09 13:15 UTC, wistefan commented on charts/api-umbrella/templates/configmap.yaml
> +{{ if .Values.umbrella.jws.root_ca -}}
Wouldn't it be better to use a secret here, instead of a configmap?

2021-06-09 13:15 UTC, wistefan commented on charts/business-api-ecosystem/templates/biz-ecosystem-charging-backend/deployment.yaml
> +        {{- if .Values.bizEcosystemChargingBackend.token.enabled }}
Should probably a secret, too

2021-06-14 05:25 UTC, wistefan approved these changes

2021-06-14 06:15 UTC, dwendland commented
We wait with the merge until the problem with the RSS image is fixed.

2021-06-15 08:46 UTC, wistefan approved these changes

2021-08-24 08:54 UTC, merged